### ISSUE TITLE
Installation on Mac OS Sierra does not work with Python 3.

### ISSUE THREAD

**Issue by tonyinme** [NaluCFD/NaluSpack#1]
The installation on Mac OS Sierra 10.12.6 is not supported using python 3.

The following error shows up in **Step 6** when running `./install_nalu_gcc_mac.sh`:

```
==> Executing phase: ‘install’
==> Error: TypeError: a bytes-like object is required, not ‘str’
TypeError: TypeError: a bytes-like object is required, not ‘str’

/Users/lmartin1/spack/var/spack/repos/builtin/packages/boost/package.py:380, in install:
     71            # The shared libraries are not installed correctly
     72            # on Darwin; correct this
     73            if (sys.platform == ‘darwin’) and (‘+shared’ in spec):
     74                fix_darwin_install_name(prefix.lib)

```

A temporary fix was used on my local machine by commenting the following line from my `~/.bash_profile`:
```
# added by Anaconda3 4.4.0 installer
#export PATH="/Users/lmartin1/anaconda/bin:$PATH"
```

**Comment by jrood-nrel** [comment]
Thanks for reporting this. I have never tried this with Python 3 but I will see if I can be more portable with this.

**Comment by jrood-nrel** [comment]
This was a legitimate bug in Spack as shown in https://github.com/spack/spack/issues/7170 as well. The fix for this has been identified and committed with pull request https://github.com/spack/spack/pull/7329 , so I'm going to close this.
