### ISSUE TITLE
Certificates Behind Firewall

### ISSUE THREAD

**Issue by tonyinme** [NaluCFD/NaluSpack#2]
The Mac installation script only works if used with the `-k` option for spack (`do not check ssl certificates when downloading`). This seems to be a firewall issue when inside the NREL network.

**Comment by jrood-nrel** [comment]
If you run the `setup_spack.sh` script, it will copy the `config.yaml` which has ssl turned off by default because ssl has many problems in NREL.

**Comment by tonyinme** [comment]
Hey @jrood-nrel, it seems that the [yaml file](https://github.com/NaluCFD/NaluSpack/blob/master/spack_config/machines/mac_sierra/config.yaml) for Mac and Mac Sierra has this option set as True.

**Comment by jrood-nrel** [comment]
Ah, sorry! I remember this problem is at the wind site. I will just change the default. Thanks.

**Comment by tonyinme** [comment]
Yes, I am at the wind site. Great, Thanks!
